import { StyleSheet } from 'react-native';

const colors = {
  background: '#F7FAF5',
  white: '#FFFFFF',
  ink: '#15251B',
  muted: '#43564A',
  green: '#174D2B',
  greenLight: '#E6F0E5',
  border: '#A6B5A7',
  papaya: '#C94F24',
  disabled: '#D7DDD7',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  homeContent: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 28,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 26,
  },
  brandMark: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.green,
  },
  brandMarkText: {
    color: colors.white,
    fontSize: 21,
    fontWeight: '800',
  },
  brandName: {
    color: colors.green,
    fontSize: 21,
    fontWeight: '800',
  },
  intro: {
    marginBottom: 20,
  },
  eyebrow: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 9,
  },
  homeTitle: {
    color: colors.ink,
    fontSize: 30,
    lineHeight: 37,
    fontWeight: '800',
    marginBottom: 10,
  },
  bodyText: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 24,
  },
  photoFrame: {
    width: '100%',
    aspectRatio: 1.42,
    maxHeight: 285,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.white,
    marginBottom: 20,
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  emptyPreview: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  leafMark: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 23,
    backgroundColor: colors.greenLight,
    marginBottom: 12,
  },
  leafMarkText: {
    color: colors.green,
    fontSize: 28,
    fontWeight: '500',
    lineHeight: 32,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 5,
  },
  emptyHint: {
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
  },
  actionGroup: {
    gap: 10,
  },
  primaryButton: {
    minHeight: 56,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  secondaryButton: {
    minHeight: 56,
    paddingHorizontal: 18,
    borderWidth: 2,
    borderColor: colors.green,
    borderRadius: 8,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.green,
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  analyzeButton: {
    minHeight: 56,
    marginTop: 4,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: colors.papaya,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disabledButton: {
    backgroundColor: colors.disabled,
  },
  disabledButtonText: {
    color: '#334238',
  },
  buttonPressed: {
    opacity: 0.82,
  },
  permissionScreen: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
    gap: 18,
    backgroundColor: colors.background,
  },
  permissionAccent: {
    color: colors.green,
  },
  permissionTitle: {
    color: colors.ink,
    fontSize: 25,
    fontWeight: '800',
    textAlign: 'center',
  },
  permissionText: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  backButton: {
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: colors.green,
    fontSize: 16,
    fontWeight: '700',
  },
  cameraScreen: {
    flex: 1,
    backgroundColor: '#101510',
  },
  cameraHeader: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    backgroundColor: colors.green,
  },
  cameraBackButton: {
    minWidth: 66,
    minHeight: 48,
    justifyContent: 'center',
  },
  cameraBackText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '700',
  },
  cameraHeading: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '700',
  },
  cameraHeaderSpacer: {
    width: 66,
  },
  cameraPreview: {
    flex: 1,
  },
  cameraControls: {
    minHeight: 148,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#101510',
  },
  cameraTip: {
    color: colors.white,
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 15,
  },
  shutterButton: {
    width: 72,
    height: 72,
    borderWidth: 4,
    borderColor: colors.white,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterInner: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.white,
  },
  shutterIndicator: {
    color: colors.white,
  },
  resultContent: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 30,
  },
  resultTitle: {
    color: colors.ink,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    marginBottom: 16,
  },
  resultImage: {
    width: '100%',
    aspectRatio: 1.55,
    maxHeight: 300,
    borderRadius: 8,
    backgroundColor: colors.greenLight,
    marginBottom: 20,
  },
  resultHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  resultDiseaseGroup: {
    flex: 1,
  },
  resultLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 5,
  },
  diseaseName: {
    color: colors.ink,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
  },
  confidenceBadge: {
    minWidth: 88,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: colors.greenLight,
  },
  confidenceValue: {
    color: colors.green,
    fontSize: 20,
    fontWeight: '800',
  },
  confidenceLabel: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '600',
  },
  resultSection: {
    paddingTop: 18,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  resultBody: {
    flex: 1,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 23,
  },
  recommendationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginTop: 9,
  },
  recommendationNumber: {
    width: 24,
    height: 24,
    overflow: 'hidden',
    borderRadius: 12,
    backgroundColor: colors.greenLight,
    color: colors.green,
    fontSize: 13,
    lineHeight: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  simulationNote: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 18,
    marginBottom: 16,
  },
});